### ISSUE TITLE
Documents not working

### ISSUE THREAD

**Issue by xX-MoonWalker-Xx** [EhsanFox/IRPayments#1]
The documents page seems to be removed, please update it in the readme if its changed

**Comment by EhsanFox** [comment]
![image](https://user-images.githubusercontent.com/20506391/216669079-05b476e5-11d9-45d4-b6b2-2e175baf86b3.png)
Seems to be fine with me!

**Comment by xX-MoonWalker-Xx** [comment]
![Screenshot_20230203-223052_Chrome](https://user-images.githubusercontent.com/72574462/216685522-e9fb5218-bf70-45aa-b794-ccfd06ed99d8.jpg)
The link in the readme is incorrect then, its https://ehsan.js.org/irpayments/
but it shows a 404 error, seems like the url is case-sensitive
